#!/bin/dash

[ "$6" = "verbose" ] && verbose='v' || verbose=''

if [ -d "$1" ]; then
    tree -aC "$1"
    exit 0
fi

exists() {
    command -v "$1" >/dev/null
}

preview_image() {
    if [ -n "$verbose" ]; then
        preview_mediainfo "$1"
    elif [ -n "$FIFO_UEBERZUG" ]; then
        printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
        exit 1
    elif exists chafa; then
        [ -n "${TMUX:-}" ] && c=240 || c=full
        [ "$2" -le 0 ] && w=$(tput cols) || w=$(($2-4))
        [ "$3" -le 0 ] && h=$(($(tput lines)-1)) || h=$3
        chafa -c $c -s ${w}x${h} -f symbols "$1"
    else
        preview_mediainfo "$1"
    fi
}

preview_mediainfo() {
    case "$(readlink -f "$1")" in
        *.webp) exists exiftool && { exiftool "$1"; return; }
    esac
    if exists mediainfo; then
        if [ -n "$verbose" ]; then
            mediainfo "$1"
        else
            mediainfo "$1" | sed -E 's/^(.{25})([^:]*): (.+)/\1 : \3/'
        fi
    elif exists exiftool; then
        exiftool "$1"
    else
        echo "Install mediainfo or exiftool"
    fi
}

preview_appimage() {
    if [ ! -x "$1" ]; then
        echo "'$1' is not executable : cannot list files!"
        exit 0
    fi
    mountpoint="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}/lf-appimage-mountpoint-$$"
    rm -f "$mountpoint"
    mkfifo "$mountpoint"
    "$1" --appimage-mount > "$mountpoint" &
    read appdir < "$mountpoint"
    files='' && [ -n "$appdir" ] && files=$(cd "$appdir" && find . -ls)
    kill $!
    rm -f "$mountpoint"
    [ -n "$files" ] && echo "$files" || return 1
}

batorcat() {
    if exists bat; then
        [ -n "$verbose" ] && w='auto' || w='never'
        bat -pp -f --wrap=$w "$1"
    elif exists highlight; then
        highlight -O ansi "$1" 2>/dev/null || cat "$1"
    else
        cat "$1"
    fi
}

case "$(readlink -f "$1")" in
    *.bmp|*.gif|*.jpg|*.jpeg|*.png|*.webp)
        preview_image "$1" "$2" "$3" "$4" "$5" ;;
    *.six|*.svg|*.xpm)
        cachefile=$1
        if [ -n "$FIFO_UEBERZUG" ] && exists convert; then
            iname=$(basename "$1")
            cachefile="${FIFO_UEBERZUG%/fifo}/image-${iname%.*}.jpg"
            convert "$1" "$cachefile"
        fi
        preview_image "$cachefile" "$2" "$3" "$4" "$5" ;;
    *.tiff)
        preview_mediainfo "$1" ;;
    *.avi|*.m4v|*.mkv|*.mp3|*.mp4)
        preview_mediainfo "$1" ;;
    *.pdf)
        pdftotext "$1" - ;;
    *.odt|*.ods|*.odp|*.sxw)
        odt2txt "$1" ;;
    *.doc)
        catdoc "$1" ;;
    *.docx)
        docx2txt "$1" - ;;
    *.[1-8])
        man "$1" | col -b ;;
    *.o)
        nm "$1" ;;
    *.md)
        glow -s dark "$1" ;;
    *.tar.zst|*.tzst)
        tar -I zstd -t${verbose}f "$1" ;;
    *.tar|*.tar.*|*.tbz|*.tbz2|*.tgz|*.txz)
        tar -t${verbose}f "$1" ;;
    *.zip)
        [ -n "$verbose" ] && zipinfo "$1" || zipinfo -1 "$1" ;;
    *.rar)
        [ -n "$verbose" ] && unrar l "$1" || unrar lb "$1" ;;
    *.gz)
        [ -n "$verbose" ] && gunzip -l -v "$1" || gunzip -l "$1" ;;
    *.7z|*.iso|*.jar)
        7z l "$1" ;;
    *.deb)
        ar t${verbose} "$1" ;;
    *.AppImage|*.appimage)
        [ -n "$verbose" ] && preview_appimage "$1" 2>/dev/null || batorcat "$1" ;;
    *.torrent)
        exists transmission-show && transmission-show "$1" || batorcat "$1" ;;
    *)
        batorcat "$1" ;;
esac
exit 0
