if command -v bat &>/dev/null; then
    alias bat='bat -p'
    alias -g -- --help='--help | bat --language=help --style=plain' 2>/dev/null
fi
alias bc="bc -l ${XDG_CONFIG_HOME:-$HOME/.config}/bc/bcrc"
alias bm='bashmount'
alias cal='cal -mw' && command -v ncal >/dev/null && alias cal='ncal -Mwb'
alias cd-='cd -'
alias cd..='cd ../'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias -- -='cd -'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias cp='cp -i'
alias df='df -h'
alias d='dirs -v'
alias diff='diff --color=always --palette=":ad=32;1:de=31;1"'
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias egrep='egrep --color=auto'
alias fd='fd --hyperlink'
alias fdi='find 2>/dev/null . -type d -iname'
alias ffi='find 2>/dev/null . -type f -iname'
alias Fdi='find 2>/dev/null . -type d -name'
alias Ffi='find 2>/dev/null . -type f -name'
alias free='free -h'
alias fgrep='fgrep --color=auto'
alias gau='git add --update'
alias gb='git branch'
alias gba='git branch --all'
alias gc='git commit'
alias gd='git diff'
alias gds='git diff --staged'
alias gst='git status'
alias grep='grep --color=auto'
alias h="history${ZSH_VERSION+ 1}"
alias hs="history${ZSH_VERSION+ 1} | grep -i"
alias hsc="history${ZSH_VERSION+ 1} | grep"
alias ip='ip -color=auto'
alias ls='ls --group-directories-first --color=auto'
alias l='ls -lFh'
alias la='ls -A'
alias ll='ls -alFh'
alias lt='ls -lFhtr'
alias ldot='ls -ld .*'
alias mv='mv -i'
alias ncal='ncal -bMw'
alias reboot='reboot -i'
alias rm='rm -i'
alias trl='trash-list'
alias trm='trash-put'
alias trr='trash-restore'
alias v='nvim'
