#!/bin/dash

system() {
    systemctl "$@"
    xsetroot -cursor_name watch 2>/dev/null
    sleep 2147483647
}

xsettingsd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
colortemp
tearfree
picom &
dunst &
setbg &
dsblocks &
dwm-pulsedaemon
easyeffects --service-mode --hide-window &
set-chromium-frame off &
set-firefox-titlebar off &
udiskie &
lf -server &
dwm-lock start &

# dwm exit codes: 0 = quit, 100 = restart, 101 = poweroff, 102 = reboot
while [ ${exitcode:-100} -eq 100 ]; do
    dwm; exitcode=$?
done

setbg --clear
dwm-lock stop
killall -q xsettingsd polkit-gnome-authentication-agent-1
killall -q picom dunst dsblocks pactl easyeffects udiskie
killall -q lf; rm -f "${XDG_RUNTIME_DIR}"/lf.*.sock
sleep 0.1

case $exitcode in
    101) system poweroff ;;
    102) system reboot ;;
esac
